VideoCell/Column implementation
robustness-gym/mosaic pull request #63
Opened 2021-06-08 20:11 UTC by tchainzzz

Uses `opencv2` to implement a video cell and column. Equipped with temporal cropping/downsampling transformations as well.

2021-06-08 20:18 UTC, krandiash commented
This branch will need to be rebased on the latest changes from `dev`: the PR should be made onto `dev`. @seyuboglu could you peek in and take a look?

2021-06-09 05:33 UTC, seyuboglu requested changes
Looks great! 
There's a `.swp` file that was accidentally committed and should be removed. Other than that lgtm. 
I agree that we should be able to specify a custom loader, but we can punt to a future PR.

2021-06-09 05:33 UTC, seyuboglu commented on mosaic/cells/video.py
> +            frames = self._read_all_frames()  # TODO: support different decoders
+1 on this TODO

2021-06-09 05:33 UTC, seyuboglu commented on mosaic/contrib/video_corruptions/transforms.py
> +    Examples:
Awesome documentation!

2021-06-09 05:33 UTC, seyuboglu commented on mosaic/contrib/video_corruptions/transforms.py
> +        # output shape: (10, C, 16, H, W)
What's C here?

2021-06-09 05:33 UTC, seyuboglu commented on mosaic/cells/video.py
> +import os
`.test_video.py.swp` was accidentally committed, we should remove it

2021-06-09 05:33 UTC, seyuboglu commented on mosaic/cells/video.py
> +            frames = self._read_all_frames()  # TODO: support different decoders
We should save for a future PR though

2021-06-09 22:51 UTC, merged